springdoc:
  api-docs:
    path: /openapi
server:
  port: 3000

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/liquibase/changeLog-master.xml
    enabled: true
